import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {StateStore} from '../src/state.mjs';
import {IntelligenceIndex, parseQuery} from '../src/intelligence.mjs';
import {NotificationMonitor, HsmDaemon} from '../src/daemon.mjs';
import {WorktreeManager} from '../src/projects.mjs';
import {SessionHubModel} from '../src/model.mjs';
import {providerInvocation,RagLocator} from '../src/rag.mjs';
import {normalizeKey,render} from '../src/tui.mjs';

function temp(prefix='hsm-1-'){return fs.mkdtempSync(path.join(os.tmpdir(),prefix));}
function store(){return new StateStore({dir:temp()});}
function session(id='s1'){return{id,harness:'claude',harnessName:'Claude Code',title:'Fix auth race',project:'api',cwd:process.cwd(),branch:'main',updatedAt:100,resume:{command:'claude',args:['--resume',id]},capabilities:{preview:true},git:{branch:'main',dirty:false}};}
function adapter(rows=[session()]){return{id:'claude',name:'Claude Code',available:()=>true,sessions:async()=>rows,preview:async()=>[{role:'user',text:'Investigate src/auth/login.js race condition'},{role:'assistant',text:'Fixed the token refresh race'}]};}

test('legacy JSON state and events migrate once with recoverable backups',()=>{const dir=temp();fs.writeFileSync(path.join(dir,'state.json'),JSON.stringify({sessions:{'claude:s1':{pinned:true}},ui:{view:'browser'}}));fs.writeFileSync(path.join(dir,'events.jsonl'),`${JSON.stringify({harness:'claude',sessionId:'s1',type:'waiting',timestamp:10})}\n`);const migrated=new StateStore({dir});assert.equal(migrated.metadata('claude:s1').pinned,true);assert.equal(migrated.events()[0].type,'waiting');assert.ok(fs.existsSync(path.join(dir,'state.json.pre-sqlite-backup')));assert.ok(fs.existsSync(path.join(dir,'events.jsonl.pre-sqlite-backup')));assert.equal(migrated.integrity(),'ok');});

test('local transcript index searches content and facets without external services',async()=>{const state=store(),index=new IntelligenceIndex(state),row=session();await index.indexSessions([row],[adapter()]);assert.equal(index.search('token refresh')[0].sessionId,'s1');assert.equal(index.search('race harness:claude')[0].role,'user');assert.equal(index.search('project:api')[0].sessionId,'s1');assert.equal(index.search('project:API')[0].sessionId,'s1');assert.equal(index.search(`project:${path.basename(process.cwd())}`)[0].sessionId,'s1');assert.equal(index.search('harness:CLAUDE branch:MAIN')[0].sessionId,'s1');assert.deepEqual(parseQuery('fix project:api'),{terms:'fix',facets:{project:'api'}});assert.equal(index.status().sessions,1);});

test('notification monitor deduplicates and honors snooze',()=>{let now=100,notices=[];const state=new StateStore({dir:temp(),now:()=>now});const monitor=new NotificationMonitor(state,{now:()=>now,notify:(title)=>notices.push(title)});state.appendEvent({harness:'claude',sessionId:'s1',type:'waiting',timestamp:100});assert.equal(monitor.tick(),1);assert.equal(monitor.tick(),0);now=200;state.appendEvent({harness:'claude',sessionId:'s1',type:'failed',timestamp:200});state.updateSession('claude:s1',{snoozedUntil:300});assert.equal(monitor.tick(),0);now=301;assert.equal(monitor.tick(),1);assert.equal(notices.length,2);});

test('worktree mutations preview before execution and dirty cleanup is blocked',()=>{const root=temp('hsm-git-');execFileSync('git',['init','-q',root]);execFileSync('git',['-C',root,'config','user.email','test@example.com']);execFileSync('git',['-C',root,'config','user.name','Test']);fs.writeFileSync(path.join(root,'README'),'one');execFileSync('git',['-C',root,'add','.']);execFileSync('git',['-C',root,'commit','-qm','init']);const manager=new WorktreeManager(),target=path.join(temp(),'feature');const preview=manager.create({root,target,branch:'feature'});assert.equal(preview.confirmationRequired,true);manager.create({root,target,branch:'feature',confirm:true});fs.writeFileSync(path.join(target,'README'),'dirty');const cleanup=manager.cleanup({root,target,confirm:true});assert.equal(cleanup.allowed,false);assert.deepEqual(cleanup.preview.blockers,['dirty']);});

test('daemon installer creates an optional systemd user unit',()=>{const dir=temp(),calls=[];const daemon=new HsmDaemon(store(),{unitDir:dir,executable:process.execPath,exec:(command,args)=>{calls.push([command,args]);return'';}});const status=daemon.install();assert.equal(status.installed,true);assert.match(fs.readFileSync(path.join(dir,'hsm.service'),'utf8'),/daemon run/);assert.ok(calls.some(([,args])=>args.includes('enable')));});

test('two views, transient finder, snooze lane and latest-session navigation work together',async()=>{const state=store(),model=new SessionHubModel({adapters:[adapter()],store:state,processScanner:()=>[]});await model.load();await model.key('2');assert.equal(model.view,'projects');model.openSessionFinder(false);model.query='token';model.runLocalSearch();assert.equal(model.rows()[0].type,'search');model.selectedSession=0;model.snoozeSelected(1000);assert.ok(model.selected().local.snoozedUntil);assert.deepEqual(model.launchSession(model.selected()),{type:'open',method:'current',command:'claude',args:['--resume','s1'],cwd:process.cwd(),sessionKey:'claude:s1',label:'Claude Code'});model.returnToLatestSession();assert.equal(model.view,'projects');assert.equal(model.selected().id,'s1');});

test('RAG locator sends redacted candidates and rejects invented session IDs',async()=>{const state=store(),index=new IntelligenceIndex(state),row=session();const secretAdapter={...adapter(),preview:async()=>[{role:'user',text:'Fix token=sk-abcdefghijklmnopqrstuvwxyz in src/auth/login.js'}]};await index.indexSessions([row],[secretAdapter]);let prompt='';const locator=new RagLocator(index,{commandExists:()=>true,run:async(_provider,value)=>{prompt=value;return JSON.stringify({matches:[{sessionKey:'claude:s1',confidence:92,reason:'Auth token race',evidence:'src/auth/login.js'},{sessionKey:'claude:invented',confidence:100}]});}});const result=await locator.find('where did we fix the authentication race',{provider:'claude'});assert.equal(result.matches.length,1);assert.equal(result.matches[0].sessionKey,'claude:s1');assert.match(prompt,/\[REDACTED\]/);assert.doesNotMatch(prompt,/sk-abcdefghijklmnopqrstuvwxyz/);});

test('Search view toggles between local and evidence-backed AI session cards',async()=>{const state=store(),model=new SessionHubModel({adapters:[adapter()],store:state,processScanner:()=>[]});await model.load();model.setView('search');model.query='authentication race';model.runLocalSearch();model.finderFocus='results';model.rag={preview:()=>({provider:'claude',candidateCount:3}),find:async()=>({provider:'claude',matches:[{sessionKey:'claude:s1',harness:'claude',sessionId:'s1',title:'Fix auth race',project:'api',confidence:91,reason:'Matches authentication race',matchedEvidence:'Fixed token refresh race'}]})};await model.key('A');assert.equal(model.rows()[0].type,'ai-search');assert.equal(model.selected().id,'s1');assert.match(render(model),/91%/);assert.match(render(model),/AI SESSION MATCH/);await model.key('A');assert.equal(model.searchMode,'local');assert.match(render(model),/LOCAL INDEX/);});

test('Finder explains filter-only queries and makes message authors visually distinct',async()=>{const state=store(),model=new SessionHubModel({adapters:[adapter()],store:state,processScanner:()=>[]});await model.load();model.setView('search');model.query='project:api';model.runLocalSearch();const screen=render(model);assert.equal(model.rows()[0].result.sessionId,'s1');assert.match(screen,/Search  ▌/);assert.match(screen,/project: api/);assert.match(screen,/\[YOU\] api · Investigate/);assert.match(screen,/\[ASSISTANT\] api · Fixed/);});

test('shifted letter key events preserve uppercase shortcuts',()=>{assert.equal(normalizeKey({name:'a',sequence:'a',shift:true}),'A');assert.equal(normalizeKey({name:'a',sequence:'A',shift:false}),'A');});

test('AI shortcut is inactive until slash opens the transient finder',async()=>{const model=new SessionHubModel({adapters:[adapter()],store:store(),processScanner:()=>[]});await model.load();await model.key('A');assert.equal(model.view,'dashboard');assert.equal(model.prompt,false);await model.key('/');assert.equal(model.view,'search');assert.equal(model.prompt,false);await model.key('esc');assert.equal(model.view,'dashboard');});

test('slash opens inline search and Tab enters directly editable filters',async()=>{const model=new SessionHubModel({adapters:[adapter()],store:store(),processScanner:()=>[]});await model.load();await model.key('/');assert.equal(model.view,'search');assert.equal(model.prompt,false);for(const key of ['t','o','k','e','n','space','r','e','f','r','e','s','h'])await model.key(key);assert.equal(model.query,'token refresh');assert.equal(model.rows()[0].result.sessionId,'s1');await model.key('tab');assert.equal(model.finderFocus,'filters');assert.equal(model.finderFilterIndex,0);for(const key of ['a','p','i'])await model.key(key);assert.match(model.query,/project:api/);await model.key('tab');assert.equal(model.finderFilterIndex,1);for(const key of ['c','l','a','u','d','e'])await model.key(key);assert.match(model.query,/harness:claude/);assert.match(render(model),/harness: claude▌/);});

test('Claude RAG invocation is ephemeral, hook-isolated, tool-free, and keeps its prompt positional',()=>{const prompt='locate my session',invocation=providerInvocation('claude',prompt);assert.equal(invocation.args[0],prompt);assert.ok(invocation.args.includes('--no-session-persistence'));assert.ok(invocation.args.includes('--setting-sources'));assert.ok(invocation.args.includes('{"hooks":{}}'));assert.ok(invocation.args.includes('--tools'));assert.ok(invocation.args.includes('--max-budget-usd'));});
