import fs from 'node:fs';
import path from 'node:path';
import {execFileSync, spawn} from 'node:child_process';
import {quote} from './state.mjs';

export const PROFILE_SCHEMA_VERSION=1;
export function projectKey(root) { try { return execFileSync('git',['-C',root,'rev-parse','--show-toplevel'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim(); } catch { return path.resolve(root); } }
export class ProjectProfiles {
  constructor(store,{exec=execFileSync}={}) { this.store=store; this.execFile=exec; }
  list(root='') { const where=root ? ` where project_key=${quote(projectKey(root))}` : ''; return this.store.query(`select id,project_key as projectKey,name,data,modified_at as modifiedAt from profiles${where} order by name`).map((row)=>({...JSON.parse(row.data),id:row.id,projectKey:row.projectKey,name:row.name,modifiedAt:row.modifiedAt})); }
  get(id) { return this.list().find((profile)=>profile.id===id)||this.list().find((profile)=>profile.name===id)||null; }
  save(profile) { validateProfile(profile); const root=projectKey(profile.root); const item={version:PROFILE_SCHEMA_VERSION,id:profile.id||slug(`${path.basename(root)}-${profile.name}`),name:profile.name,root,baseBranch:profile.baseBranch||'',launches:profile.launches||[],tmux:profile.tmux||null,terminalFallback:profile.terminalFallback!==false}; this.store.exec(`insert or replace into profiles values(${quote(item.id)},${quote(root)},${quote(item.name)},${quote(JSON.stringify(item))},${Date.now()})`); return item; }
  duplicate(id,name) { const source=this.get(id); if(!source) throw new Error(`Profile not found: ${id}`); return this.save({...source,id:'',name}); }
  export(id,target) { const item=this.get(id); if(!item) throw new Error(`Profile not found: ${id}`); const safe={...item,launches:item.launches.map(({env,...launch})=>({...launch,env:Object.fromEntries(Object.keys(env||{}).map((key)=>[key,'']))}))}; fs.writeFileSync(target,`${JSON.stringify(safe,null,2)}\n`,{mode:0o600}); return target; }
  import(file,{confirm=false}={}) { if(!confirm) return {confirmationRequired:true,preview:JSON.parse(fs.readFileSync(file,'utf8'))}; return this.save(JSON.parse(fs.readFileSync(file,'utf8'))); }
  run(id,{tmux=true}={}) { const profile=this.get(id); if(!profile) throw new Error(`Profile not found: ${id}`); if(tmux&&profile.tmux&&commandExists('tmux',this.execFile)) return launchTmux(profile,this.execFile); const children=[],[terminal,...terminalArgs]=(process.env.TERMINAL||'xdg-terminal-exec').split(/\s+/);for(const launch of profile.launches){const cwd=path.resolve(profile.root,launch.cwd||'.'); const child=spawn(terminal,[...terminalArgs,launch.command,...(launch.args||[])],{cwd,env:{...process.env,...launch.env},detached:true,stdio:'ignore'});child.unref();children.push(child.pid);} return {backend:'terminal',pids:children}; }
}
export class WorktreeManager {
  constructor({exec=execFileSync}={}){this.exec=exec;}
  inspect(root){const top=projectKey(root),quiet={encoding:'utf8',stdio:['ignore','pipe','pipe']};const raw=this.exec('git',['-C',top,'worktree','list','--porcelain'],quiet);let merged=[];try{merged=this.exec('git',['-C',top,'branch','--merged','HEAD','--format=%(refname:short)'],quiet).trim().split('\n');}catch{}return raw.trim().split('\n\n').filter(Boolean).map((block)=>{const lines=block.split('\n');const item={path:lines[0].slice(9),head:'',branch:'',detached:false,missing:false,dirty:false,merged:false};for(const line of lines.slice(1)){if(line.startsWith('HEAD '))item.head=line.slice(5);if(line.startsWith('branch '))item.branch=line.slice(7).replace('refs/heads/','');if(line==='detached')item.detached=true;}item.merged=Boolean(item.branch&&merged.includes(item.branch));item.missing=!fs.existsSync(item.path);if(!item.missing)try{item.dirty=Boolean(this.exec('git',['-C',item.path,'status','--porcelain'],quiet).trim());}catch{}return item;});}
  create({root,target,branch,base='HEAD',confirm=false}){const preview={root:projectKey(root),target:path.resolve(target),branch,base};if(!confirm)return{confirmationRequired:true,preview};this.exec('git',['-C',preview.root,'worktree','add','-b',branch,preview.target,base],{stdio:'inherit'});return preview;}
  cleanup({root,target,confirm=false,activeCwds=[]}){const item=this.inspect(root).find((row)=>row.path===path.resolve(target));if(!item)throw new Error(`Worktree not found: ${target}`);const active=activeCwds.some((cwd)=>cwd===item.path||cwd.startsWith(`${item.path}/`));const blockers=[item.dirty?'dirty':'',active?'active session':''].filter(Boolean);const preview={...item,blockers};if(!confirm||blockers.length)return{confirmationRequired:true,allowed:blockers.length===0,preview};this.exec('git',['-C',projectKey(root),'worktree','remove',item.path]);return{removed:item.path};}
}
export function validateProfile(profile){if(!profile?.name||!profile?.root)throw new Error('Profile requires name and root.');if(!fs.existsSync(profile.root))throw new Error(`Profile root does not exist: ${profile.root}`);for(const launch of profile.launches||[])if(!launch.command)throw new Error('Each profile launch requires a command.');return true;}
function launchTmux(profile,exec){const name=slug(profile.name),first=profile.launches[0];if(!first)throw new Error('A tmux profile requires at least one launch.');exec('tmux',['new-session','-d','-s',name,'-c',path.resolve(profile.root,first.cwd||'.'),...launchArgs(first)]);for(const launch of profile.launches.slice(1))exec('tmux',['split-window','-t',name,'-c',path.resolve(profile.root,launch.cwd||'.'),...launchArgs(launch)]);exec('tmux',['select-layout','-t',name,profile.tmux.layout||'tiled']);return{backend:'tmux',session:name,attach:['tmux','attach','-t',name]};}
function launchArgs(launch){const env=Object.entries(launch.env||{}).map(([key,value])=>`${key}=${value}`);return env.length?['env',...env,launch.command,...(launch.args||[])]:[launch.command,...(launch.args||[])];}
function commandExists(command,exec){try{exec('which',[command],{stdio:'ignore'});return true;}catch{return false;}}
function slug(value){return String(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);}
