import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';

export function projectKey(root) { try { return execFileSync('git',['-C',root,'rev-parse','--show-toplevel'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim(); } catch { return path.resolve(root); } }
export class WorktreeManager {
  constructor({exec=execFileSync}={}){this.exec=exec;}
  inspect(root){const top=projectKey(root),quiet={encoding:'utf8',stdio:['ignore','pipe','pipe']};const raw=this.exec('git',['-C',top,'worktree','list','--porcelain'],quiet);let merged=[];try{merged=this.exec('git',['-C',top,'branch','--merged','HEAD','--format=%(refname:short)'],quiet).trim().split('\n');}catch{}return raw.trim().split('\n\n').filter(Boolean).map((block)=>{const lines=block.split('\n');const item={path:lines[0].slice(9),head:'',branch:'',detached:false,missing:false,dirty:false,merged:false};for(const line of lines.slice(1)){if(line.startsWith('HEAD '))item.head=line.slice(5);if(line.startsWith('branch '))item.branch=line.slice(7).replace('refs/heads/','');if(line==='detached')item.detached=true;}item.merged=Boolean(item.branch&&merged.includes(item.branch));item.missing=!fs.existsSync(item.path);if(!item.missing)try{item.dirty=Boolean(this.exec('git',['-C',item.path,'status','--porcelain'],quiet).trim());}catch{}return item;});}
  create({root,target,branch,base='HEAD',confirm=false}){const preview={root:projectKey(root),target:path.resolve(target),branch,base};if(!confirm)return{confirmationRequired:true,preview};this.exec('git',['-C',preview.root,'worktree','add','-b',branch,preview.target,base],{stdio:'inherit'});return preview;}
  cleanup({root,target,confirm=false,activeCwds=[]}){const item=this.inspect(root).find((row)=>row.path===path.resolve(target));if(!item)throw new Error(`Worktree not found: ${target}`);const active=activeCwds.some((cwd)=>cwd===item.path||cwd.startsWith(`${item.path}/`));const blockers=[item.dirty?'dirty':'',active?'active session':''].filter(Boolean);const preview={...item,blockers};if(!confirm||blockers.length)return{confirmationRequired:true,allowed:blockers.length===0,preview};this.exec('git',['-C',projectKey(root),'worktree','remove',item.path]);return{removed:item.path};}
}
